version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: opensimplebank
      POSTGRES_PASSWORD: password
      POSTGRES_DB: opensimplebank
    ports:
      - 6969:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    
volumes:
   postgres: